boot.o: boot.S multiboot.h x86_desc.h types.h
interrupts.o: interrupts.S
x86_desc.o: x86_desc.S x86_desc.h types.h
filesys.o: filesys.c filesys.h types.h lib.h pcb.h
i8259.o: i8259.c i8259.h types.h lib.h
idt.o: idt.c idt.h x86_desc.h types.h lib.h rtc.h interrupts.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h idt.h rtc.h interrupts.h paging.h keyboard.h
keyboard.o: keyboard.c keyboard.h types.h lib.h i8259.h
lib.o: lib.c lib.h types.h
paging.o: paging.c types.h paging.h
rtc.o: rtc.c rtc.h types.h i8259.h lib.h
terminal.o: terminal.c terminal.h types.h keyboard.h lib.h i8259.h rtc.h \
  filesys.h pcb.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h rtc.h
